## Intro to Pandas
+ Object Creation
+ Viewing data
+ Selection
+ Missing data
+ Grouping
+ Reshaping
+ Time series
+ Plotting
+ i/o

pandas.pydata.org


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
%matplotlib inline

In [4]:
demo_2d = np.arange(24)
print(type(demo_2d))
print(demo_2d.shape)
demo_2d

<class 'numpy.ndarray'>
(24,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [5]:
demo_2d = np.arange(24).reshape(-1,2)
print(type(demo_2d))
print(demo_2d.shape)
demo_2d

<class 'numpy.ndarray'>
(12, 2)


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

### Q: Why is -1 the same as 12?

In [6]:
pd.DataFrame(demo_2d)   # note row and col indexes are auto-generated

0   1
0    0   1
1    2   3
2    4   5
3    6   7
4    8   9
5   10  11
6   12  13
7   14  15
8   16  17
9   18  19
10  20  21
11  22  23

In [9]:
pd.date_range?

In [7]:
# creates a DateTime index
dates = pd.date_range('20140101', periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [8]:
list('ABCD')

['A', 'B', 'C', 'D']

In [9]:
# generates 6x4 dataframe with random numbers
# assigns dates (derined above) as indexes
df = pd.DataFrame(np.random.randn(6,4), 
                  index=dates, 
                  columns=list('ABCD'))
df

A         B         C         D
2014-01-01  2.282135  0.176159  0.333273 -0.483922
2014-01-02  0.779265  0.656352  0.792056  0.268721
2014-01-03  0.538865 -0.514846  0.014668 -0.970693
2014-01-04 -0.002645  0.275872  2.029277 -2.450299
2014-01-05  0.386555  0.244199 -0.529201 -1.482292
2014-01-06  1.751137  1.761720  1.073133 -0.784839

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2014-01-01 to 2014-01-06
Freq: D
Data columns (total 4 columns):
A    6 non-null float64
B    6 non-null float64
C    6 non-null float64
D    6 non-null float64
dtypes: float64(4)
memory usage: 240.0 bytes


In [11]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.955885  0.433243  0.618868 -0.983887
std    0.876285  0.753671  0.893341  0.922774
min   -0.002645 -0.514846 -0.529201 -2.450299
25%    0.424632  0.193169  0.094319 -1.354392
50%    0.659065  0.260036  0.562664 -0.877766
75%    1.508169  0.561232  1.002864 -0.559151
max    2.282135  1.761720  2.029277  0.268721

In [12]:
df.describe

<bound method NDFrame.describe of                    A         B         C         D
2014-01-01  2.282135  0.176159  0.333273 -0.483922
2014-01-02  0.779265  0.656352  0.792056  0.268721
2014-01-03  0.538865 -0.514846  0.014668 -0.970693
2014-01-04 -0.002645  0.275872  2.029277 -2.450299
2014-01-05  0.386555  0.244199 -0.529201 -1.482292
2014-01-06  1.751137  1.761720  1.073133 -0.784839>

In [13]:
# index, columns, underlying numpy data
df

A         B         C         D
2014-01-01  2.282135  0.176159  0.333273 -0.483922
2014-01-02  0.779265  0.656352  0.792056  0.268721
2014-01-03  0.538865 -0.514846  0.014668 -0.970693
2014-01-04 -0.002645  0.275872  2.029277 -2.450299
2014-01-05  0.386555  0.244199 -0.529201 -1.482292
2014-01-06  1.751137  1.761720  1.073133 -0.784839

In [14]:
df.transpose()

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    2.282135    0.779265    0.538865   -0.002645    0.386555    1.751137
B    0.176159    0.656352   -0.514846    0.275872    0.244199    1.761720
C    0.333273    0.792056    0.014668    2.029277   -0.529201    1.073133
D   -0.483922    0.268721   -0.970693   -2.450299   -1.482292   -0.784839

In [15]:
# shorthand for transpose
df.T

2014-01-01  2014-01-02  2014-01-03  2014-01-04  2014-01-05  2014-01-06
A    2.282135    0.779265    0.538865   -0.002645    0.386555    1.751137
B    0.176159    0.656352   -0.514846    0.275872    0.244199    1.761720
C    0.333273    0.792056    0.014668    2.029277   -0.529201    1.073133
D   -0.483922    0.268721   -0.970693   -2.450299   -1.482292   -0.784839

In [16]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [17]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [18]:
df.values

array([[ 2.28213475,  0.1761588 ,  0.33327271, -0.48392167],
       [ 0.77926526,  0.65635244,  0.792056  ,  0.26872101],
       [ 0.53886464, -0.51484609,  0.01466764, -0.9706931 ],
       [-0.00264466,  0.27587236,  2.02927714, -2.45029852],
       [ 0.38655478,  0.24419874, -0.52920094, -1.48229215],
       [ 1.75113737,  1.76171968,  1.07313326, -0.78483929]])

### New Example

In [19]:
pd.Series(1, 
          index=list(range(4)), 
          dtype='float32')

0    1.0
1    1.0
2    1.0
3    1.0
dtype: float32

In [20]:
df2 = pd.DataFrame(
    { 'A' : 1.,
      'B' : pd.Timestamp('20130102'),
      'C' : pd.Series(1, index=list(range(4)), dtype='float32'),
      'D' : np.array([3] * 4, dtype='int32'),
      'E' : 'foo'})
df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [21]:
# with specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

### Viewing Data

In [22]:
df.head(1)

A         B         C         D
2014-01-01  2.282135  0.176159  0.333273 -0.483922

In [23]:
df.tail(2)

A         B         C         D
2014-01-05  0.386555  0.244199 -0.529201 -1.482292
2014-01-06  1.751137  1.761720  1.073133 -0.784839

In [24]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [25]:
# Note: columns are also of type 'Index'
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

### Quick summary statistics

In [26]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.955885  0.433243  0.618868 -0.983887
std    0.876285  0.753671  0.893341  0.922774
min   -0.002645 -0.514846 -0.529201 -2.450299
25%    0.424632  0.193169  0.094319 -1.354392
50%    0.659065  0.260036  0.562664 -0.877766
75%    1.508169  0.561232  1.002864 -0.559151
max    2.282135  1.761720  2.029277  0.268721

In [27]:
percentiles = np.arange(0, 1, 0.1)
print(type(percentiles))
percentiles

<class 'numpy.ndarray'>


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [28]:
# convert to list
percentiles=list(percentiles)
print(type(percentiles))
percentiles

<class 'list'>


[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9]

In [29]:
percentiles = np.arange(0, 1, 0.1)
df.describe(percentiles=list(percentiles))  # instead of 25%, 50%, 75% => 10%, 20%, 30%, ,,,

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.955885  0.433243  0.618868 -0.983887
std    0.876285  0.753671  0.893341  0.922774
min   -0.002645 -0.514846 -0.529201 -2.450299
0%    -0.002645 -0.514846 -0.529201 -2.450299
10%    0.191955 -0.169344 -0.257267 -1.966295
20%    0.386555  0.176159  0.014668 -1.482292
30.0%  0.462710  0.210179  0.173970 -1.226493
40%    0.538865  0.244199  0.333273 -0.970693
50%    0.659065  0.260036  0.562664 -0.877766
60.0%  0.779265  0.275872  0.792056 -0.784839
70%    1.265201  0.466112  0.932595 -0.634380
80%    1.751137  0.656352  1.073133 -0.483922
90%    2.016636  1.209036  1.551205 -0.107600
max    2.282135  1.761720  2.029277  0.268721

In [30]:
df.sort_values(by=['B', 'D'], ascending=False)

A         B         C         D
2014-01-06  1.751137  1.761720  1.073133 -0.784839
2014-01-02  0.779265  0.656352  0.792056  0.268721
2014-01-04 -0.002645  0.275872  2.029277 -2.450299
2014-01-05  0.386555  0.244199 -0.529201 -1.482292
2014-01-01  2.282135  0.176159  0.333273 -0.483922
2014-01-03  0.538865 -0.514846  0.014668 -0.970693

### Selection

In [40]:
type(df['A'])   # series vs. data frame

pandas.core.series.Series

In [41]:
df['A'].shape

(6,)

In [42]:
df['A']

2014-01-01    2.282135
2014-01-02    0.779265
2014-01-03    0.538865
2014-01-04   -0.002645
2014-01-05    0.386555
2014-01-06    1.751137
Freq: D, Name: A, dtype: float64

In [43]:
type(df[['A']])  # data frame - careful: get different type depending on selection

pandas.core.frame.DataFrame

In [44]:
df[['A']].shape

(6, 1)

In [45]:
df[['A']]

A
2014-01-01  2.282135
2014-01-02  0.779265
2014-01-03  0.538865
2014-01-04 -0.002645
2014-01-05  0.386555
2014-01-06  1.751137

In [48]:
df[0:3]

A         B         C         D
2014-01-01  2.282135  0.176159  0.333273 -0.483922
2014-01-02  0.779265  0.656352  0.792056  0.268721
2014-01-03  0.538865 -0.514846  0.014668 -0.970693

In [53]:
# by label
dates[2]

Timestamp('2014-01-03 00:00:00', freq='D')

In [57]:
df.loc[dates[0]]   # select the first row, get back a pd.Series

A    2.282135
B    0.176159
C    0.333273
D   -0.483922
Name: 2014-01-01 00:00:00, dtype: float64

In [59]:
df.loc[dates[2], 'B']

-0.5148460933241946

In [60]:
df.loc['2014-01-01', 'B']

0.17615880320385316

In [61]:
df.iloc[0, 1]   # iloc - locate by index - [row 0, col 1]

0.17615880320385316

In [62]:
# multi-axis by label
df.loc[:, ['A', 'D']]   # [ all rows, cols A and D ]

A         D
2014-01-01  2.282135 -0.483922
2014-01-02  0.779265  0.268721
2014-01-03  0.538865 -0.970693
2014-01-04 -0.002645 -2.450299
2014-01-05  0.386555 -1.482292
2014-01-06  1.751137 -0.784839

In [63]:
# Date Range
df.loc['20140102': '20140104', ['B', 'D']]

B         D
2014-01-02  0.656352  0.268721
2014-01-03 -0.514846 -0.970693
2014-01-04  0.275872 -2.450299

In [64]:
# fast access to scalar
df.at[dates[1], 'B']

0.6563524382868461

In [66]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-04 -0.002645  0.275872  2.029277 -2.450299
2014-01-05  0.386555  0.244199 -0.529201 -1.482292
2014-01-06  1.751137  1.761720  1.073133 -0.784839

### Boolean Indexing

In [70]:
df[(df.A>0) | (df.B<0)]   # basically a 'where' operation

A         B         C         D
2014-01-01  2.282135  0.176159  0.333273 -0.483922
2014-01-02  0.779265  0.656352  0.792056  0.268721
2014-01-03  0.538865 -0.514846  0.014668 -0.970693
2014-01-05  0.386555  0.244199 -0.529201 -1.482292
2014-01-06  1.751137  1.761720  1.073133 -0.784839

### Setting (Assignment)

In [71]:
df

A         B         C         D
2014-01-01  2.282135  0.176159  0.333273 -0.483922
2014-01-02  0.779265  0.656352  0.792056  0.268721
2014-01-03  0.538865 -0.514846  0.014668 -0.970693
2014-01-04 -0.002645  0.275872  2.029277 -2.450299
2014-01-05  0.386555  0.244199 -0.529201 -1.482292
2014-01-06  1.751137  1.761720  1.073133 -0.784839

In [73]:
# make a copy so original dataset is not affected
df_posA = df.copy()
df_posA[df_posA.A<0] = 4 # converting negative values in 'A' to positive
df_posA

A         B         C         D
2014-01-01  2.282135  0.176159  0.333273 -0.483922
2014-01-02  0.779265  0.656352  0.792056  0.268721
2014-01-03  0.538865 -0.514846  0.014668 -0.970693
2014-01-04  4.000000  4.000000  4.000000  4.000000
2014-01-05  0.386555  0.244199 -0.529201 -1.482292
2014-01-06  1.751137  1.761720  1.073133 -0.784839

In [74]:
# Setting new column - auto aligns data by index
s1 = pd.Series([1,2,3,4,5,6],
              index=pd.date_range('20140102', periods=6))
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [75]:
df['F'] = s1

In [76]:
# notice missing value in first row for col 'F'!
df

A         B         C         D    F
2014-01-01  2.282135  0.176159  0.333273 -0.483922  NaN
2014-01-02  0.779265  0.656352  0.792056  0.268721  1.0
2014-01-03  0.538865 -0.514846  0.014668 -0.970693  2.0
2014-01-04 -0.002645  0.275872  2.029277 -2.450299  3.0
2014-01-05  0.386555  0.244199 -0.529201 -1.482292  4.0
2014-01-06  1.751137  1.761720  1.073133 -0.784839  5.0

#### What happened to s1's 6th row?

### Missing Data
NaN is the same as null

In [84]:
# Add a column with missing data (on subset of df, just rows [0:4])
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])
df1

A         B         C         D    F   E
2014-01-01  2.282135  0.176159  0.333273 -0.483922  NaN NaN
2014-01-02  0.779265  0.656352  0.792056  0.268721  1.0 NaN
2014-01-03  0.538865 -0.514846  0.014668 -0.970693  2.0 NaN
2014-01-04 -0.002645  0.275872  2.029277 -2.450299  3.0 NaN

In [85]:
df1.loc[dates[0]:dates[1],'E'] = 1
df1

A         B         C         D    F    E
2014-01-01  2.282135  0.176159  0.333273 -0.483922  NaN  1.0
2014-01-02  0.779265  0.656352  0.792056  0.268721  1.0  1.0
2014-01-03  0.538865 -0.514846  0.014668 -0.970693  2.0  NaN
2014-01-04 -0.002645  0.275872  2.029277 -2.450299  3.0  NaN

In [86]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

In [87]:
df1.isnull()   # same as above

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [89]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean   0.955885  0.433243  0.618868 -0.983887  3.000000
std    0.876285  0.753671  0.893341  0.922774  1.581139
min   -0.002645 -0.514846 -0.529201 -2.450299  1.000000
25%    0.424632  0.193169  0.094319 -1.354392  2.000000
50%    0.659065  0.260036  0.562664 -0.877766  3.000000
75%    1.508169  0.561232  1.002864 -0.559151  4.000000
max    2.282135  1.761720  2.029277  0.268721  5.000000

In [90]:
df.mean()   # axis=0 default

A    0.955885
B    0.433243
C    0.618868
D   -0.983887
F    3.000000
dtype: float64

In [93]:
df.mean(axis=1)   # operation on two different axes ???

2014-01-01    0.576911
2014-01-02    0.699279
2014-01-03    0.213599
2014-01-04    0.570441
2014-01-05    0.523852
2014-01-06    1.760230
Freq: D, dtype: float64

### Applying Functions

In [92]:
df

A         B         C         D    F
2014-01-01  2.282135  0.176159  0.333273 -0.483922  NaN
2014-01-02  0.779265  0.656352  0.792056  0.268721  1.0
2014-01-03  0.538865 -0.514846  0.014668 -0.970693  2.0
2014-01-04 -0.002645  0.275872  2.029277 -2.450299  3.0
2014-01-05  0.386555  0.244199 -0.529201 -1.482292  4.0
2014-01-06  1.751137  1.761720  1.073133 -0.784839  5.0

In [94]:
df.apply(np.cumsum)   # cumulative sum, downward

A         B         C         D     F
2014-01-01  2.282135  0.176159  0.333273 -0.483922   NaN
2014-01-02  3.061400  0.832511  1.125329 -0.215201   1.0
2014-01-03  3.600265  0.317665  1.139996 -1.185894   3.0
2014-01-04  3.597620  0.593538  3.169273 -3.636192   6.0
2014-01-05  3.984175  0.837736  2.640073 -5.118484  10.0
2014-01-06  5.735312  2.599456  3.713206 -5.903324  15.0

In [95]:
df.apply(lambda x: x.max() - x.min(), axis=1)

2014-01-01    2.766056
2014-01-02    0.731279
2014-01-03    2.970693
2014-01-04    5.450299
2014-01-05    5.482292
2014-01-06    5.784839
Freq: D, dtype: float64

In [98]:
# Built-in string methods
s = pd.Series(['A','B','C','Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s

0       A
1       B
2       C
3    Aaba
4    Baca
5     NaN
6    CABA
7     dog
8     cat
dtype: object

In [99]:
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge


#### Pandas concat Vs append Vs join Vs merge
Concat gives the flexibility to join based on the axis( all rows or all columns) Append is the specific case(axis=0, join='outer') of concat Join is based on the indexes (set by set_index) on how variable =['left','right','inner','couter'] Merge is based on any particular column each of the two dataframes, this columns are variables on like 'left_on', 'right_on', 'on'

http://py-tut.blogspot.com/2016/11/pandas-concat-and-append.html

In [102]:
np.random.randn(10,4)

array([[-0.06465169, -0.23640727, -0.38570702,  0.22681482],
       [-0.80803457,  1.10886064, -0.03905283, -2.07321185],
       [-0.9792788 , -1.04006157, -0.39718015, -0.03693264],
       [ 0.12038492, -0.1022652 , -0.30882594, -0.85608779],
       [-0.81476132, -1.89235715,  0.38478799, -1.41999091],
       [-2.09188825,  0.86520702, -0.98946528, -1.37292412],
       [ 0.05957284, -0.37640958,  0.44821545, -2.68694622],
       [ 0.70271508,  0.42892059, -1.34826718,  2.30105186],
       [ 0.55105787,  0.14182819,  0.52831586,  0.77206213],
       [ 1.56518334, -1.83418548,  0.50967951,  0.10681002]])

In [103]:
df

A         B         C         D    F
2014-01-01  2.282135  0.176159  0.333273 -0.483922  NaN
2014-01-02  0.779265  0.656352  0.792056  0.268721  1.0
2014-01-03  0.538865 -0.514846  0.014668 -0.970693  2.0
2014-01-04 -0.002645  0.275872  2.029277 -2.450299  3.0
2014-01-05  0.386555  0.244199 -0.529201 -1.482292  4.0
2014-01-06  1.751137  1.761720  1.073133 -0.784839  5.0

In [105]:
# concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -1.395019  0.271439  1.228600 -0.604910
1 -0.440246  1.315329  0.529013 -1.338103
2  1.874924  0.395465 -0.146880 -0.364830
3 -1.059657  1.040597  0.470151  0.812560
4 -0.029454  0.631258  1.724369  0.979566
5  0.235698  0.189931  2.133224 -1.210595
6  1.016155 -0.507300  1.454796  1.828196
7  0.691590  0.205939  0.326756 -1.182701
8 -1.628920  1.925323 -0.385860  1.381261
9 -0.013584  0.752325  1.565173 -0.745301

In [106]:
# break into pieces
piece_1 = df[:3]
piece_2 = df[3:7]
piece_3 = df[7:]
print(piece_1)
print(piece_2)
print(piece_3)

          0         1         2         3
0 -1.395019  0.271439  1.228600 -0.604910
1 -0.440246  1.315329  0.529013 -1.338103
2  1.874924  0.395465 -0.146880 -0.364830
          0         1         2         3
3 -1.059657  1.040597  0.470151  0.812560
4 -0.029454  0.631258  1.724369  0.979566
5  0.235698  0.189931  2.133224 -1.210595
6  1.016155 -0.507300  1.454796  1.828196
          0         1         2         3
7  0.691590  0.205939  0.326756 -1.182701
8 -1.628920  1.925323 -0.385860  1.381261
9 -0.013584  0.752325  1.565173 -0.745301


In [107]:
pd.concat([piece_1, piece_2, piece_3])

0         1         2         3
0 -1.395019  0.271439  1.228600 -0.604910
1 -0.440246  1.315329  0.529013 -1.338103
2  1.874924  0.395465 -0.146880 -0.364830
3 -1.059657  1.040597  0.470151  0.812560
4 -0.029454  0.631258  1.724369  0.979566
5  0.235698  0.189931  2.133224 -1.210595
6  1.016155 -0.507300  1.454796  1.828196
7  0.691590  0.205939  0.326756 -1.182701
8 -1.628920  1.925323 -0.385860  1.381261
9 -0.013584  0.752325  1.565173 -0.745301

In [108]:
# Also can "Join" and "Append"
piece_1.append(piece_2)

0         1         2         3
0 -1.395019  0.271439  1.228600 -0.604910
1 -0.440246  1.315329  0.529013 -1.338103
2  1.874924  0.395465 -0.146880 -0.364830
3 -1.059657  1.040597  0.470151  0.812560
4 -0.029454  0.631258  1.724369  0.979566
5  0.235698  0.189931  2.133224 -1.210595
6  1.016155 -0.507300  1.454796  1.828196

In [109]:
piece_1.T.join(piece_2.T)

0         1         2         3         4         5         6
0 -1.395019 -0.440246  1.874924 -1.059657 -0.029454  0.235698  1.016155
1  0.271439  1.315329  0.395465  1.040597  0.631258  0.189931 -0.507300
2  1.228600  0.529013 -0.146880  0.470151  1.724369  2.133224  1.454796
3 -0.604910 -1.338103 -0.364830  0.812560  0.979566 -1.210595  1.828196

### Grouping