In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (8, 6)
plt.rcParams['font.size'] = 14
plt.style.use("fivethirtyeight")

Perfect Fit - y values are equal to 2*X. Betas are optimized so that there is no residual error.

In [2]:
df = pd.DataFrame([[2,4],[4,8],[6,12]])

In [3]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [4]:
df.columns = ['X','y']

In [5]:
df.X

0    2
1    4
2    6
Name: X, dtype: int64

In [6]:
df.y

0     4
1     8
2    12
Name: y, dtype: int64

In [7]:
lr.fit(pd.DataFrame(df["X"]),df["y"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
lr.intercept_

2.6645352591003757e-15

In [9]:
lr.coef_

array([ 2.])

In [10]:
lr.predict(pd.DataFrame(df["X"]))

array([  4.,   8.,  12.])

Imperfect Fit - y values are not equal to 2*X. Betas are optimized to minimize residual error.

In [11]:
df = pd.DataFrame([[2,4],[4,8],[6,11]])

In [12]:
df.columns = ['X','y']

In [13]:
lr = LinearRegression()

In [14]:
df.X

0    2
1    4
2    6
Name: X, dtype: int64

In [15]:
df.y

0     4
1     8
2    11
Name: y, dtype: int64

In [16]:
lr.fit(pd.DataFrame(df["X"]),df["y"])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
lr.intercept_

0.66666666666666785

In [18]:
lr.coef_

array([ 1.75])

In [19]:
lr.predict(pd.DataFrame(df["X"]))   # for X = [2, 4, 6]

array([  4.16666667,   7.66666667,  11.16666667])